name: Sync Repository to AWS CodeCommit
description: Syncs a repository to AWS CodeCommit using AWS Credentials authorized through GitHub OIDC token.
author: Nathan Stern
branding:
  color: yellow
  icon: activity

inputs:
  role-to-assume:
    description: The ARN for AWS IAM Role to be assumed while making requests to AWS CodeCommit
    required: true
  repository:
    description: The name of repository being synced
    required: false
    default: ${{ github.repository }}
  aws-region:
    description: The AWS region that the CodeCommitRepository is in
    required: false
    default: us-east-1

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        fetch-depth: 0
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
    - name: Sync Repository
      run: |
        set +x
        repository_name="$(echo "${{ inputs.repository }}" | sed 's/.*\///g')"
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        output_json="$(aws codecommit get-repository --repository-name "$repository_name")"
        if [ $? -ne 0 ]; then
          output_json="$(aws codecommit create-repository --repository-name "$repository_name")"
        fi
        if [ $? -ne 0 ]; then
          echo "Could not create repository $repository_name"
          exit 1
        fi
        clone_url="$(echo "$output_json" | python3 -c "import sys, json; print(json.load(sys.stdin)['repositoryMetadata']['cloneUrlHttp'])")"
        git remote add codecommit "$clone_url"
        git push codecommit --force --mirror
      shell: bash
